# Generated by Django 3.2 on 2025-01-11 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activation_code',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_registration_code_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
