# Generated by Django 3.2 on 2025-01-11 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20250111_0309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='date_registration_code_created',
            new_name='validity_code',
        ),
    ]
