# Generated by Django 3.2 on 2025-01-18 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_activation_code_customuser_confirmation_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
