# Generated by Django 3.2 on 2025-01-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20250111_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
